"""Writes data/shots.json, the single source of truth for the pilot.

Every other script reads shots.json: the Blender blockout builder, the 2D FX
compositor, the sheet builder and the doc generator. Edit the data here (or the
JSON directly) and re-run the pipeline.

World layout (metres): Pandava host at y < -110 facing +Y, Kaurava host at
y > +90 facing -Y, empty ground between. Arjuna's car stands at (0, -100) in
front of the Pandava line, or at (0, -6) once it is "between the two armies".
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

ACTS = {
    "A": {
        "name": "Dawn of war",
        "mood": "awe, pride, noise",
        "key": "#F2B36B", "shadow": "#4A2F45", "accent": "#E8862A",
        "sky": ["#FFE2B0", "#F2B36B", "#D9826E", "#8C4F6A", "#3E2A48"],
        "haze": "#F4C99A", "haze_dist": 480, "ground": "#C89A64",
        "sun_dir": [0.25, 1.0, 0.07], "key_dir": [0.35, 0.9, 0.45],
        "rim": "#FFD9A0", "rim_dir": [0.25, 1.0, 0.25], "grain": 0.025,
        "prompt": "Act A palette: apricot dawn, dusty gold haze, warm violet-brown shadows, saffron accents.",
    },
    "B": {
        "name": "Stillness",
        "mood": "doubt, grief",
        "key": "#9AA7B4", "shadow": "#2A3340", "accent": "#E8C15A",
        "sky": ["#B9C2C9", "#9AA7B4", "#7D8995", "#56606C", "#2E3640"],
        "haze": "#A9B3BC", "haze_dist": 180, "ground": "#8E8A7E",
        "sun_dir": [0.2, 1.0, 0.6], "key_dir": [0.3, -0.2, 1.0],
        "rim": "#C9D2DA", "rim_dir": [-0.5, 0.8, 0.3], "grain": 0.04,
        "prompt": "Act B palette: desaturated blue-grey, hidden sun, cold slate shadows; the only warm color is a thin gold rim on Krishna.",
    },
    "C": {
        "name": "Vishvarupa",
        "mood": "terror, wonder",
        "key": "#FFF2C4", "shadow": "#120B2E", "accent": "#2FD3C6",
        "sky": ["#3B1F5C", "#2A1450", "#1A0C3A", "#120B2E", "#07051A"],
        "haze": "#2B1A55", "haze_dist": 400, "ground": "#2A2140",
        "sun_dir": [0.0, 1.0, 0.55], "key_dir": [0.0, 1.0, 0.7],
        "rim": "#7FF5EA", "rim_dir": [0.0, 1.0, 0.5], "grain": 0.03,
        "prompt": "Act C palette: black-violet cosmos, white-gold core light, teal, magenta and gold sacred geometry.",
    },
    "D": {
        "name": "War dawn",
        "mood": "resolve",
        "key": "#FF7A2E", "shadow": "#3A1A12", "accent": "#6FC3FF",
        "sky": ["#FFD36B", "#FF9A3C", "#E8562A", "#8E2A22", "#3A1A12"],
        "haze": "#F08A4A", "haze_dist": 220, "ground": "#9A5A34",
        "sun_dir": [-0.3, -1.0, 0.1], "key_dir": [-0.3, -1.0, 0.35],
        "rim": "#FFB070", "rim_dir": [-0.3, -1.0, 0.2], "grain": 0.03,
        "prompt": "Act D palette: hot orange sun, red dust, burnt umber shadows, electric blue energy on Arjuna.",
    },
}

CHARACTERS = {
    "krishna": {"name": "Krishna", "skin": "#2E3F78", "costume": "#E8B92F", "accent": "#1E8C8C", "energy": "#FFE9A8",
                "prompt": "Krishna: deep indigo-blue skin, calm almond eyes, faint smile, yellow silk dhoti and upper cloth, low gold crown with a single peacock feather, gold necklaces and armlets, white-gold divine energy with teal edge"},
    "arjuna": {"name": "Arjuna", "skin": "#8A5A3C", "costume": "#C9CED6", "accent": "#2C5C9C", "energy": "#6FC3FF",
               "prompt": "Arjuna: young archer, warm brown skin, sharp brows, curly black hair, white and silver scale armor, blue sash, very tall dark horn-and-gold bow (Gandiva), electric blue lightning energy"},
    "bhishma": {"name": "Bhishma", "skin": "#C9A27E", "costume": "#E9ECEF", "accent": "#C9A23A", "energy": "#CDEFF2",
                "prompt": "Bhishma: towering elderly warrior, long white beard and hair, white and silver armor, plain brow band, silver-white energy with river-aqua edge"},
    "duryodhana": {"name": "Duryodhana", "skin": "#7A5A3A", "costume": "#9E1B2F", "accent": "#C9A23A", "energy": "#D0213F",
                   "prompt": "Duryodhana: broad heavy-shouldered prince, crimson and black armor with heavy gold ornament, mace on shoulder, blood-red energy"},
    "bhima": {"name": "Bhima", "skin": "#5A3A28", "costume": "#E07A1F", "accent": "#5A5F66", "energy": "#9FE3C1",
              "prompt": "Bhima: massive warrior, dark umber skin, bare powerful arms, saffron dhoti, iron bands, huge mace, wind green-cyan energy"},
    "yudhishthira": {"name": "Yudhishthira", "skin": "#7E5A40", "costume": "#EDE3CC", "accent": "#2C4A8C", "energy": "#F3DCA0",
                     "prompt": "Yudhishthira: calm upright king, cream dhoti with royal blue upper cloth, modest crown, white royal parasol, steady pale gold energy"},
}

CONCHES = {
    "panchajanya": {"owner": "krishna", "color": "#FFF4D0"},
    "devadatta": {"owner": "arjuna", "color": "#6FC3FF"},
    "paundra": {"owner": "bhima", "color": "#9FE3C1"},
    "anantavijaya": {"owner": "yudhishthira", "color": "#F3DCA0"},
    "bhishma": {"owner": "bhishma", "color": "#CDEFF2"},
}


def shot(id, beat, act, dur, title, desc, cam, staging, fx, *, hero=False, impact=None,
         sound="", source="", keyframe="", motion="", dialogue=""):
    return dict(id=id, beat=beat, act=act, duration=dur, title=title, description=desc,
                camera=cam, staging=staging, fx=fx, hero=hero, impact=impact, sound=sound,
                source=source, keyframe_prompt=keyframe, motion_prompt=motion, dialogue=dialogue)


SHOTS = [
    shot("SH010", 1, "A", 7.0, "The field at dawn",
         "Wide, long lens, from behind the Pandava host. Two hosts face each other across a bare stripe of earth; standards to the horizon; the low sun sits behind the Kaurava host and turns the dust gold. Arjuna's ape banner rises above every standard.",
         dict(lens=45, loc=[-14, -200, 12], target=[0, 60, 9], move="slow crane down and push in", roll=0),
         dict(chariot="front"),
         [dict(type="sun"), dict(type="godrays", anchor="sun", color="#FFE2B0", count=14, alpha=0.22),
          dict(type="glow", anchor="arjuna.banner", color="#FFD27A", r=0.03, alpha=0.6),
          dict(type="dust", color="#F4C99A")],
         hero=True, sound="Wind, banners cracking, distant horses, no music.",
         source="B06 lines 2963-2964 (ape banner above all standards)",
         keyframe="wide long-lens shot from behind an ancient Indian army at dawn, two vast armies facing each other across a bare dusty plain, thousands of banners, low sun behind the far army, golden dust haze, one giant ape-emblem banner rising above all others, tiny figures, epic scale",
         motion="slow crane down and push in over the army toward the empty ground, banners rippling, dust drifting low, 7 seconds"),
    shot("SH020", 1, "A", 4.0, "The ape banner",
         "Low and long-lens: the gold ape standard on Arjuna's car fills the upper frame, silhouetted against the dawn sun, the banner snapping in the wind.",
         dict(lens=70, loc=[5, -122, 1.4], target=[0, -100.6, 9.2], move="locked, slight drift up", roll=-3, sky_scale=4.0),
         dict(chariot="front", sun_dir=[-0.12, 0.92, 0.36]),
         [dict(type="sun"), dict(type="flare", anchor="sun", color="#FFE2B0"),
          dict(type="godrays", anchor="sun", color="#FFE9C0", count=10, alpha=0.25)],
         sound="Single deep drum hit on the cut.", source="B06 lines 2963-2964, 3212",
         keyframe="low angle long lens shot of a tall chariot standard topped by a crouching golden ape emblem, saffron banner snapping in wind, silhouetted against a low dawn sun, lens flare",
         motion="banner snaps and ripples, sun flare breathes, very slight upward drift, 4 seconds"),
    shot("SH030", 2, "A", 4.0, "The grandsire's roar",
         "Bhishma, white-bearded and towering on his white car, throws his head back and gives a lion's roar, conch raised high. Duryodhana watches from his car with fierce joy.",
         dict(lens=28, loc=[-19.5, 93.0, 1.4], target=[-12, 96.5, 3.0], move="slow push in", roll=4),
         dict(chariot="front", poses=dict(bhishma="roar", duryodhana="mace")),
         [dict(type="halo", anchor="bhishma.head", color="#CDEFF2", r=0.10, alpha=0.35),
          dict(type="dust", color="#F4C99A")],
         source="B06 lines 3475-3478", sound="Bhishma's roar, then a breath of silence.",
         keyframe="low angle medium shot of a towering elderly warrior with long white beard on a white chariot, head thrown back in a lion's roar, holding a white conch high, white and silver armor, tall palmyra standard behind, army banners and dust",
         motion="warrior throws head back and roars, raises the conch, beard and cloth whip in wind, slow push in, 4 seconds"),
    shot("SH040", 2, "A", 3.0, "Bhishma's conch",
         "Bhishma blows. Silver-aqua sound rings burst from the conch; the Kaurava host behind him erupts with conches, drums, cymbals and horns.",
         dict(lens=50, loc=[-16, 91, 2.6], target=[-12, 96, 2.85], move="locked, camera shake on the blast", roll=0),
         dict(chariot="front", poses=dict(bhishma="conch", duryodhana="mace")),
         [dict(type="rings", anchor="bhishma.conch", color="#CDEFF2", count=7, r0=0.04, r1=0.6, width=0.006, squash=0.75),
          dict(type="speedlines", anchor="bhishma.conch", color="#FFFFFF", count=40, alpha=0.35)],
         impact=dict(anchor="bhishma.conch", color="#CDEFF2", frames=2),
         source="B06 lines 3476-3478", sound="Bhishma's conch, then the whole Kaurava host: conches, drums, cymbals, horns.",
         keyframe="side view of a white-bearded warrior blowing a large white conch, concentric silver-aqua sound rings bursting outward as hand-drawn 2D effects, army erupting behind",
         motion="conch blast, sound rings expand outward on twos, camera shake, 3 seconds"),
    shot("SH050", 3, "A", 5.0, "Like a thousand suns",
         "Hero shot: Arjuna's car, decked with gold and a hundred bells, four white steeds, the ape banner overhead. The sun strikes it full on and it blazes. Krishna holds the reins; Arjuna stands with Gandiva.",
         dict(lens=35, loc=[13, -93.0, 1.0], target=[0, -99.3, 2.6], move="low tracking arc left to right", roll=-2),
         dict(chariot="front", poses=dict(krishna="reins", arjuna="bow_rest")),
         [dict(type="glow", anchor="arjuna.chariot", color="#FFD27A", r=0.35, alpha=0.35),
          dict(type="sparkles", anchor="arjuna.chariot", color="#FFF2C4", count=60, r=0.3),
          dict(type="dust", color="#F4C99A")],
         hero=True, source="B06 lines 3208-3213",
         sound="Bells, hooves stamping, a rising choir note.",
         keyframe="heroic low angle three-quarter shot of an ornate golden Indian war chariot with two large spoked wheels and a hundred small bells, four white horses, a tall ape-emblem banner, blue-skinned charioteer in yellow silk holding the reins, young archer in white and silver armor holding a very tall bow, blazing in direct sunlight, gold glints",
         motion="low tracking arc around the chariot, horses stamp and toss their heads, bells shiver, gold glints, 5 seconds"),
    shot("SH060", 3, "A", 3.0, "Panchajanya and Devadatta",
         "Front two-shot, locked and symmetrical: Krishna lifts the white Panchajanya, Arjuna lifts Devadatta.",
         dict(lens=50, loc=[0.0, -93.0, 2.6], target=[0, -100, 2.6], move="locked", roll=0),
         dict(chariot="front", poses=dict(krishna="conch_lift", arjuna="conch_lift"), hide=["horses"]),
         [dict(type="halo", anchor="krishna.head", color="#FFE9A8", r=0.09, alpha=0.5)],
         source="B06 lines 3478-3481", sound="Breath, cloth, one held drone note.",
         keyframe="symmetrical front two-shot on a golden chariot, blue-skinned divine charioteer in yellow silk and a young archer in silver armor each lifting a white conch shell, faint golden halo behind the charioteer",
         motion="both lift their conches to their lips in unison, locked camera, 3 seconds"),
    shot("SH070", 3, "A", 4.0, "They blow together",
         "Low three-quarter: Krishna and Arjuna blow. White-gold and electric-blue rings interlock and roll out over the field. Impact frame on the blast.",
         dict(lens=30, loc=[5.5, -93.5, 0.6], target=[0, -99.8, 2.9], move="locked, then camera shake", roll=-6),
         dict(chariot="front", poses=dict(krishna="conch", arjuna="conch"), hide=["horses"]),
         [dict(type="rings", anchor="krishna.conch", color="#FFF4D0", count=7, r0=0.03, r1=0.75, width=0.007, squash=0.8),
          dict(type="rings", anchor="arjuna.conch", color="#6FC3FF", count=6, r0=0.03, r1=0.65, width=0.006, squash=0.8, phase=0.5),
          dict(type="speedlines", anchor="krishna.conch", color="#FFFFFF", count=48, alpha=0.3)],
         hero=True, impact=dict(anchor="krishna.conch", color="#FFE9A8", frames=3),
         source="B06 lines 3478-3481", sound="Two conches, perfectly in tune, then a low boom.",
         keyframe="low three-quarter shot of a blue-skinned divine charioteer and a young archer blowing white conch shells on a golden chariot, interlocking white-gold and electric-blue concentric sound rings exploding outward as hand-drawn 2D effects",
         motion="conch blast, two sets of sound rings expand and interlock on twos, cloth and hair blown back, 4 seconds"),
    shot("SH080", 4, "A", 5.0, "Paundra and Anantavijaya",
         "Bhima blows the huge Paundra, green wind rings tearing up dust; behind him Yudhishthira, under his white parasol, blows Anantavijaya in pale gold. The twins' conches answer down the line.",
         dict(lens=35, loc=[-22.5, -101.0, 1.6], target=[-33, -107.5, 2.9], move="whip pan from Bhima to Yudhishthira", roll=3),
         dict(chariot="front", poses=dict(bhima="conch", yudhishthira="conch")),
         [dict(type="rings", anchor="bhima.conch", color="#9FE3C1", count=8, r0=0.03, r1=0.8, width=0.009, squash=0.7),
          dict(type="rings", anchor="yudhishthira.conch", color="#F3DCA0", count=5, r0=0.02, r1=0.35, width=0.004, squash=0.8),
          dict(type="dust", color="#F4C99A")],
         source="B06 lines 3481-3484", sound="Paundra: a huge, rough blast. Anantavijaya: clean and high.",
         keyframe="massive warrior with dark skin and saffron dhoti blowing a huge ribbed conch, green-cyan wind rings tearing up dust; behind him a calm king under a white parasol blowing a gold-banded conch with pale gold rings",
         motion="whip pan from the massive warrior's blast to the king under the parasol, rings expand on twos, 5 seconds"),
    shot("SH090", 5, "A", 5.0, "The blare",
         "Reverse: from among the Kaurava soldiers, a wall of colored sound rings rolls across the sky toward camera and the ground shakes. Foreground soldiers recoil. Impact frame.",
         dict(lens=20, loc=[14, 128, 2.2], target=[0, -100, 14], move="handheld, violent shake", roll=5),
         dict(chariot="front"),
         [dict(type="sun"),
          dict(type="shockwave", anchor="arjuna.chariot", color="#FFF4D0"),
          dict(type="rings", anchor="arjuna.chariot", color="#FFF4D0", count=6, r0=0.05, r1=1.4, width=0.006, squash=0.35),
          dict(type="rings", anchor="arjuna.chariot", color="#6FC3FF", count=5, r0=0.07, r1=1.2, width=0.005, squash=0.35, phase=0.5),
          dict(type="speedlines", anchor="arjuna.chariot", color="#FFFFFF", count=60, alpha=0.25),
          dict(type="dust", color="#F4C99A")],
         hero=True, impact=dict(anchor="arjuna.chariot", color="#FFE9A8", frames=3),
         source="B06 lines 3488-3490 (the blare 'rent the hearts' of the Kaurava host)",
         sound="Every conch at once, reverb across the plain, then a sub-bass hit.",
         keyframe="ultra wide shot from behind a crowd of soldiers in dark armor, across a dusty plain a wall of white-gold and blue concentric sound rings rolling across the sky toward camera, ground dust lifting in a shockwave",
         motion="sound wave rolls toward camera, soldiers in foreground recoil, violent handheld shake, 5 seconds"),
    shot("SH100", 6, "B", 5.0, "Between the two armies",
         "From behind the car: Arjuna turns to Krishna. The light has gone grey. Arjuna: \"Place my car between the two armies, so that I may observe these that stand here.\"",
         dict(lens=35, loc=[1.2, -105.5, 3.2], target=[0, -96, 2.6], move="slow push in", roll=0),
         dict(chariot="front", poses=dict(krishna="reins", arjuna="bow_rest")),
         [dict(type="halo", anchor="krishna.head", color="#E8C15A", r=0.05, alpha=0.25)],
         dialogue="Arjuna: \"Place my car between the two armies, so that I may observe these that stand here.\" (B06 lines 3498-3499)",
         source="B06 lines 3498-3508",
         keyframe="from behind a golden chariot, a young archer in silver armor turning to speak to the blue-skinned charioteer, grey overcast light, two armies ahead, muted cold colors",
         motion="slow push in, archer turns his head toward the charioteer, banners still, 5 seconds"),
    shot("SH110", 6, "B", 6.0, "The empty ground",
         "High angle: the single chariot rolls into the bare stripe of earth between the two hosts, dwarfed by them on both sides.",
         dict(lens=16, loc=[70, -6, 70], target=[0, -6, 0], move="high and locked, the car rolls into the centre", roll=0),
         dict(chariot="between", poses=dict(krishna="reins", arjuna="bow_rest")),
         [dict(type="dust", color="#A9B3BC"), dict(type="glow", anchor="arjuna.chariot", color="#E8C15A", r=0.03, alpha=0.7)],
         hero=False, source="B06 lines 3508-3510",
         sound="Wheels and hooves only; both armies silent.",
         keyframe="high angle wide view looking down at a single small chariot with four white horses on a bare stripe of earth between two vast armies, grey overcast light, cold desaturated colors",
         motion="locked high angle, the chariot rolls slowly into the center and stops, dust trails behind, 6 seconds"),
    shot("SH120", 7, "B", 5.0, "Faces of kin",
         "Over Arjuna's shoulder, long lens: Bhishma, Drona and the Kaurava princes stand in the front line, close enough to know, too far to touch.",
         dict(lens=85, loc=[-0.05, -8.6, 2.95], target=[-12, 96, 2.6], move="slow rack focus across the faces", roll=0),
         dict(chariot="between", poses=dict(krishna="reins", arjuna="bow_rest", bhishma="stand", duryodhana="mace")),
         [],
         source="B06 lines 3508-3514",
         keyframe="over-the-shoulder long lens shot past a young archer's silver shoulder toward an enemy front line where an elderly white-bearded warrior and other noble warriors stand on chariots, compressed perspective, cold grey light",
         motion="slow rack focus from the archer's shoulder to the distant elders, 5 seconds"),
    shot("SH130", 8, "B", 5.0, "Gandiva slips",
         "Side profile: Arjuna sinks down onto the car floor; the great bow slides from his hand. Krishna stands motionless at the front. Sound drops out.",
         dict(lens=50, loc=[11.5, -6.0, 1.9], target=[0, -6.0, 1.8], move="locked", roll=0),
         dict(chariot="between", poses=dict(krishna="reins", arjuna="slump"), arjuna_bow="falling"),
         [dict(type="halo", anchor="krishna.head", color="#E8C15A", r=0.03, alpha=0.3)],
         hero=True, impact=dict(anchor="arjuna.hand_l", color="#6FC3FF", frames=1),
         dialogue="Arjuna: \"My body trembles, and my hair stands on end. Gandiva slips from my hand.\" (B06 lines 3519-3521)",
         source="B06 lines 3517-3521", sound="Total silence except the bow hitting the boards.",
         keyframe="side profile of a golden chariot between two armies under grey sky, a young archer in silver armor sinking to the floor, a very tall bow slipping from his hand, the blue-skinned charioteer standing still at the front",
         motion="archer sinks down, bow slides and falls, charioteer does not move, 5 seconds"),
    shot("SH140", 9, "B", 4.0, "Krishna turns",
         "Close, locked, symmetrical: Krishna, back-lit, turns his face; a thin gold rim and the first halo ring forming behind his head.",
         dict(lens=85, loc=[0.3, -1.6, 2.8], target=[0.3, -5.55, 2.86], move="locked", roll=0),
         dict(chariot="between", poses=dict(krishna="turn", arjuna="slump"), hide=["horses", "banner"], key_dir=[0.5, 1.0, 0.6]),
         [dict(type="halo", anchor="krishna.head", color="#E8C15A", r=0.24, alpha=0.75),
          dict(type="yantra", anchor="krishna.head", color="#E8C15A", r=0.32, alpha=0.25, petals=8, faces=0)],
         source="Bhagavad Gita, B06 Sections XXV-XLII (summarized)",
         sound="A single low tanpura drone enters.",
         keyframe="symmetrical close-up of a blue-skinned divine figure with a low gold crown and single peacock feather, back-lit with a thin gold rim light, a fine golden mandala ring forming behind his head, grey overcast background",
         motion="locked, he turns his face slowly toward camera, the halo ring draws itself on, 4 seconds"),
    shot("SH150", 10, "C", 6.0, "The universal form",
         "Extreme wide, low: the sky opens. A colossal figure of light with countless arms, crowned, holding mace and discus, fills the heavens inside rotating yantra rings of faces and eyes. The chariot is a speck on the ground line.",
         dict(lens=12, loc=[6, -16, 1.0], target=[0, 400, 185], move="slow tilt up from the chariot to the form", roll=0),
         dict(chariot="between", poses=dict(krishna="reins", arjuna="stand"), vishvarupa=True),
         [dict(type="yantra", anchor="vishvarupa.head", color="#FFE9A8", r=0.3, alpha=0.9, petals=16, faces=20),
          dict(type="chakra", anchor="vishvarupa.discus", color="#FFE9A8", r=0.06),
          dict(type="glow", anchor="vishvarupa.chest", color="#FFF2C4", r=0.6, alpha=0.6),
          dict(type="godrays", anchor="vishvarupa.head", color="#FFF2C4", count=24, alpha=0.18)],
         hero=True, impact=dict(anchor="vishvarupa.head", color="#2FD3C6", frames=2),
         source="B06 lines 4826-4862 ('the splendour of a thousand suns', line 4845; 'diadem, mace, and discus', line 4860)",
         sound="A cosmic roar built from all the conches slowed down, a choir, then silence.",
         keyframe="extreme wide low angle, a tiny chariot on a thin dark horizon beneath a colossal radiant multi-armed divine figure filling the night sky, crowned, holding a mace and a spinning discus, surrounded by rotating concentric mandala rings filled with countless faces and eyes, white-gold core light, teal and magenta sacred geometry, splendour of a thousand suns",
         motion="slow tilt up from the chariot to the cosmic form, mandala rings counter-rotate, light pulses, 6 seconds"),
    shot("SH160", 10, "C", 4.0, "Arjuna beholds",
         "Over Arjuna's shoulder, close: he stands small against the light, the rings of the form turning above him.",
         dict(lens=18, loc=[0.05, -7.6, 2.5], target=[-1, 400, 160], move="slow push in", roll=2),
         dict(chariot="between", poses=dict(krishna="reins", arjuna="stand"), vishvarupa=True, hide=["horses", "banner"]),
         [dict(type="yantra", anchor="vishvarupa.head", color="#FFE9A8", r=0.34, alpha=0.8, petals=16, faces=16),
          dict(type="glow", anchor="vishvarupa.chest", color="#FFF2C4", r=0.7, alpha=0.5)],
         source="B06 lines 4843-4862",
         keyframe="over-the-shoulder shot of a young archer in silver armor looking up at a colossal radiant cosmic figure and rotating mandala rings of faces and eyes, white-gold light on his face and armor, deep violet cosmos",
         motion="slow push in past the archer's shoulder, rings turning overhead, light flickers across his armor, 4 seconds"),
    shot("SH170", 11, "D", 5.0, "Arjuna rises",
         "Back on the field in a hot orange dawn. Low angle: Arjuna rises and lifts Gandiva high; blue lightning runs along the bow. Krishna takes the reins.",
         dict(lens=24, loc=[2.6, -3.4, 1.2], target=[-0.35, -6.2, 3.0], move="low crane up with him", roll=-5),
         dict(chariot="between", poses=dict(krishna="reins", arjuna="bow_raise"), hide=["horses"]),
         [dict(type="sun"), dict(type="lightning", anchor="arjuna.bow_top", anchor2="arjuna.bow_bottom", color="#6FC3FF"),
          dict(type="glow", anchor="arjuna.hand_l", color="#6FC3FF", r=0.12, alpha=0.6),
          dict(type="dust", color="#F08A4A")],
         hero=True, dialogue="Arjuna: \"My delusion hath been destroyed.\" (B06 line 5773)",
         source="B06 line 5773 (Section XLII)", sound="Thunder roll; the war drums start.",
         keyframe="low angle heroic shot of a young archer in silver armor rising on a golden chariot and lifting a very tall bow high, crackling electric-blue lightning along the bow, hot orange sun and red dust behind him",
         motion="archer rises and raises the bow, lightning crawls along it on twos, camera cranes up with him, 5 seconds"),
    shot("SH180", 12, "D", 4.0, "The banner, then black",
         "The ape banner snaps against a red sun. Hard cut to black. Title.",
         dict(lens=85, loc=[12.9, 36.4, 4.9], target=[0, -6.55, 9.0], move="locked", roll=0),
         dict(chariot="between", poses=dict(krishna="reins", arjuna="bow_raise"), sun_dir=[-0.287, -0.955, 0.088]),
         [dict(type="sun", scale=2.2), dict(type="flare", anchor="sun", color="#FFD36B"),
          dict(type="godrays", anchor="sun", color="#FFD36B", count=12, alpha=0.25)],
         hero=True, source="B06 lines 2963-2964, 3212",
         sound="Banner crack, one conch note, cut to silence.",
         keyframe="long lens low angle of a golden ape-emblem standard and saffron banner snapping in the wind against a huge red-orange sun, red dust, silhouette",
         motion="banner snaps three times in slow motion, then hard cut to black, 4 seconds"),
]


def main():
    out = os.path.join(HERE, "..", "data", "shots.json")
    data = dict(
        project="Mahabharat series, pilot 'The First Conch'",
        source="Ganguli translation, Bhishma Parva (source/B06-bhishma.txt)",
        fps=24, fx_fps=12, aspect=2.39,
        acts=ACTS, characters=CHARACTERS, conches=CONCHES, shots=SHOTS,
    )
    with open(out, "w") as f:
        json.dump(data, f, indent=2)
    print("wrote", os.path.normpath(out), len(SHOTS), "shots,",
          sum(s["duration"] for s in SHOTS), "seconds")


if __name__ == "__main__":
    main()
